-- MySQL Script generated by MySQL Workbench
-- Tue Mar 26 13:40:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_vendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_vendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_vendas` DEFAULT CHARACTER SET utf8 ;
USE `bd_vendas` ;

-- -----------------------------------------------------
-- Table `bd_vendas`.`tbl_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_vendas`.`tbl_clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_vendas`.`tbl_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_vendas`.`tbl_produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `preco` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_vendas`.`tbl_funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_vendas`.`tbl_funcionarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_vendas`.`tbl_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_vendas`.`tbl_vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_compra` DATE NULL,
  `fk_clientes` INT NULL,
  `fk_funcionarios` INT NULL,
  `valor_total` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `tbl_vendas_tbl_cliente_idx` (`fk_clientes` ASC),
  INDEX `tbl_vendas_tbl_funcionarios_idx` (`fk_funcionarios` ASC),
  CONSTRAINT `tbl_vendas_tbl_clientes`
    FOREIGN KEY (`fk_clientes`)
    REFERENCES `bd_vendas`.`tbl_clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tbl_vendas_tbl_funcionarios`
    FOREIGN KEY (`fk_funcionarios`)
    REFERENCES `bd_vendas`.`tbl_funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_vendas`.`tbl_itens_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_vendas`.`tbl_itens_vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_produtos` INT NOT NULL,
  `fk_vendas` INT NOT NULL,
  `quantidade` DOUBLE NOT NULL,
  `valor_venda` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tbl_itens_tbl_produtos_idx` (`fk_produtos` ASC),
  INDEX `tbl_itens_tbl_vendas_idx` (`fk_vendas` ASC),
  CONSTRAINT `tbl_itens_tbl_produtos`
    FOREIGN KEY (`fk_produtos`)
    REFERENCES `bd_vendas`.`tbl_produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tbl_itens_tbl_vendas`
    FOREIGN KEY (`fk_vendas`)
    REFERENCES `bd_vendas`.`tbl_vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
